name: CI

on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath ngrok

    - name: Authenticate with Ngrok
      run: .\ngrok\ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Ngrok tunnel
      run: |
        echo "authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}" > ngrok.yml
        echo "tunnels:" >> ngrok.yml
        echo "  remote_desktop:" >> ngrok.yml
        echo "    proto: tcp" >> ngrok.yml
        echo "    addr: 3389" >> ngrok.yml
        .\ngrok\ngrok start -config ngrok.yml remote_desktop

    # Add more steps as needed for your specific workflow


